//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.WebsiteStyleGuide.Skins {
    
    
    public partial class Metadata {
        
        /// <summary>
        /// smallCss control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.ClientDependencyFramework.WebForms.Css smallCss;
        
        /// <summary>
        /// mediumCss control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.ClientDependencyFramework.WebForms.Css mediumCss;
        
        /// <summary>
        /// largeCss control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.ClientDependencyFramework.WebForms.Css largeCss;
    }
}
